---
# Source: okdp-control-plane-ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: okdp-console
  labels:
    app: okdp-console
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 4200
      protocol: TCP
  selector:
    app: okdp-console
---
# Source: okdp-control-plane-ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: okdp-console
  labels:
    app: okdp-console
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okdp-console
  template:
    metadata:
      labels:
        app: okdp-console
    spec:
      containers:
        - name: okdp-console
          image: "okdp-control-plane-ui:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4200
          readinessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 4200
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            limits:
              memory: 256Mi
              cpu: 250m
            requests:
              memory: 128Mi
              cpu: 100m
